-- Update search profile with new IS24 URL
-- Usage: sqlite3 /opt/immo_bot/data/immobot.db < scripts/update_search_url.sql

UPDATE search_profiles SET search_url = 'https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=eWt7ZEhzcGVlQXJgQG1FYlN9ZElgRklqQ2RBaElmUXRIdklCVk52QVBmQk54QVJmQlBmQlR0QlJmQlBmQkB_QkNgQkN_QUlyQkNgQkNgQkp4QlpyQ1ZkQ1xiREpkQW9Dbm1AbkVoSnBfQGNAdFx5UnJWb2hBRHFKUntBWmtDWmlDaEBxQl57QlRpQlxrQUpzQFJ5QFR3QEhjQU51QURxQVh7QUhrQmJATWBJaEBoSHxEdEl8THZGdkJoS21BcEZjRWtLcVxxU21NbU5rW3BCbUNuQmtFdENtTWhAX0pfQndYe0N9V2NId1FlTG9oQHlMeV5zQ2NPcVNfWGFLcVNlVHdbd0V1RmlKe0lnRGlCcVp3RXNsQHdWc0lzQHtMQmtKZ019WHlWaUdjSG1XfVxlSHVMcUdvSV9Fb0RhRV9DY0VvQW9KZENpS3BGZ0lkSn1IYEx1Q2pGfUB4RERqRWBCdk9wRXZSckp2VHBMdFRpb0B8UHVCbkJpRXBYa0dsS2dBekZjQWhfQGtLcFR9QmJKTWJEeEtkZ0F4QGZFZER4TGhFfElwRnhQZEh2TmRFbEdqQ2RVfktiXG5Ldm1AdElwfUBkSGRSfEBJYFBuTGBGfEJ8RHRfQHJDfmZAdkVkYEBqSXJtQHJOZ0BmTW5AfEZmRGxHfFZ2THBT&numberofrooms=2.5-&price=1500.0-3000.0&exclusioncriteria=swapflat&pricetype=calculatedtotalrent&sorting=2',
min_price = NULL,
max_price = NULL,
min_rooms = NULL
WHERE id = 2;
